pipeline {
  agent {
  docker {
    image 'node:20-alpine3.17'
    label 'docker'
  }
}

  stages {
    stage('Build') {
      steps {
        sh 'env'
      }
    }
    stage('Verify') {
      steps {
        sh 'node --version'
      }
    }
  }
}

jenkins - computers (node) - agent (node label)

docker-workflow plugin

jenkins node having label docker  (docker engine and docker cli) - java agent (jre)