pipeline {
  agent none
  stages {
    stage('Java Dev') {
      agent {
        docker { image 'adoptopenjdk/maven-openjdk11'
                label 'docker'
         }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('NodeApp Dev') {
      agent {
        docker { image 'node:20-alpine3.17' 
                label 'docker'
        }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
