{
 "title": "Jenkins: Performance and Job Details",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage, Jenkins Job Status, and lot more.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "default_jenkins_builds_success_build_count"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Processing speed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count[1m])"
    }
   ]
  },
  {
   "title": "Job queue duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jenkins_job_queuing_duration_count{instance=\"jenkins1.eng.paloaltonetworks.local:443\"}"
    }
   ]
  },
  {
   "title": "Queued rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count[1m])"
    }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_health_check_score" }
   ]
  },
  {
   "title": "Jenkins nodes offline",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_node_offline_value" }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_total_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Sucessful Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_success_total" }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_failure_total" }
   ]
  },
  {
   "title": "Unstable Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_runs_unstable_total{instance=\"jenkins1.eng.paloaltonetworks.local:443\"}"
    }
   ]
  },
  {
   "title": "Executor free",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_executor_free_value" }
   ]
  },
  {
   "title": "Executor In-use",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_executor_in_use_value" }
   ]
  },
  {
   "title": "Aborted Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_aborted_total" }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_queue_size_value" }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_job_count_value", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Total Build Nodes Available",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_node_count_value", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Total Build Nodes Offline",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_node_offline_value", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Job Duration",
   "type": "graph",
   "description": "Build times in milliseconds of last build",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_duration_milliseconds",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "HTTP Request Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_count" }
   ]
  },
  {
   "title": "Build Success Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "default_jenkins_builds_success_build_count",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Last Build Duration",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_duration_milliseconds"
    }
   ]
  },
  {
   "title": "Build Ordinal",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_result_ordinal"
    }
   ]
  },
  {
   "title": "Blocked Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(jenkins_job_blocked_duration_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocked Jobs",
   "type": "gauge",
   "description": "The number of jobs that are in the Jenkins build queue and currently in the blocked state.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_queue_blocked_value" }
   ]
  },
  {
   "title": "Job Building Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Jobs Building",
   "type": "gauge",
   "description": "The number of jobs that are in the Jenkins build queue and currently in the buildable state.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_queue_buildable_value" }
   ]
  },
  {
   "title": "Job Queuing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Job Queue Size",
   "type": "gauge",
   "description": "The number of jobs that are in the Jenkins build queue.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_queue_size_value" }
   ]
  },
  {
   "title": "Job Total Duration",
   "type": "timeseries",
   "description": "The rate at which jobs are queued and the total time they spend from entering the build queue to completing building",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(jenkins_job_total_duration_count[$__rate_interval])"
    }
   ]
  }
 ]
}